version: 2
updates:
  # Backend dependencies
  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "00WhengWheng"
    assignees:
      - "00WhengWheng"
    commit-message:
      prefix: "⬆️"
      include: "scope"
    labels:
      - "dependencies"
      - "backend"
    ignore:
      # Ignore major version updates for stable packages
      - dependency-name: "@nestjs/*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "typeorm"
        update-types: ["version-update:semver-major"]

  # Frontend dependencies
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "00WhengWheng"
    assignees:
      - "00WhengWheng"
    commit-message:
      prefix: "⬆️"
      include: "scope"
    labels:
      - "dependencies"
      - "frontend"
    ignore:
      # Ignore major version updates for UI libraries
      - dependency-name: "react*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "vite"
        update-types: ["version-update:semver-major"]

  # Root workspace dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "00WhengWheng"
    assignees:
      - "00WhengWheng"
    commit-message:
      prefix: "⬆️"
      include: "scope"
    labels:
      - "dependencies"
      - "workspace"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/server"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    reviewers:
      - "00WhengWheng"
    assignees:
      - "00WhengWheng"
    commit-message:
      prefix: "🐳"
    labels:
      - "docker"
      - "backend"

  - package-ecosystem: "docker"
    directory: "/client"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    reviewers:
      - "00WhengWheng"
    assignees:
      - "00WhengWheng"
    commit-message:
      prefix: "🐳"
    labels:
      - "docker"
      - "frontend"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
    reviewers:
      - "00WhengWheng"
    assignees:
      - "00WhengWheng"
    commit-message:
      prefix: "🔧"
    labels:
      - "github-actions"
      - "ci-cd"
